clear
clc

% Run k-Wave Simulation for Each Transmit Element

% Load Focusing Functions
addpath(genpath(pwd));
addpath(genpath('../k-Wave'));

% Load Info Needed for K-Wave Simulation
map_number = 1; % Choice of Abdominal Map
filename = ['sim_info/SimInfo', num2str(map_number), '.mat'];
load(filename)

% Parallelize Transmit Element Simulations by Job ID
fprintf('This message is sent at time %s\n', datetime)
%tx_elmt_idx = str2double(getenv('SLURM_ARRAY_TASK_ID'))
for tx_elmt_idx = 1:no_elements
    % Place Transmit Signal on Array 
    src = struct(); % ParFor Requires you to Explicitly Create A Struct
    src.u_mask = source.u_mask; 
    src.ux = ux_src_elmts(:,:,tx_elmt_idx);
    
    % Run the Simulation for Transmit
    sensor_data = kspaceFirstOrder2D(kgrid, medium, src, sensor, input_args{:});
    % Isoimpedance Method for Removing "Direct Arrival" Transmit Pulse
    sensor_data_isoimp = kspaceFirstOrder2D(kgrid, medium_isoimp, src, sensor, input_args{:});
    sensor_data_rx = sensor_data - sensor_data_isoimp;
    % Sum Sensor Recordings for Each Grid Point into Receive Elements 
    sensor_data_rx = reshape(sensor_data_rx, [no_subelem, no_elements, numel(kgrid.t_array)]);
    sensor_data_rx = squeeze(sum(sensor_data_rx, 1));
    
    % Apodize and Reformat Data
    sensor_data_rx_apod = sensor_data_rx'; apod = rectwin(no_elements);
    for elt = 1:no_elements
        sensor_data_rx_apod(:,elt) = sensor_data_rx_apod(:,elt) * apod(elt);
    end
    
    % Assemble Full Synthetic Aperture Data 
    rf_data = sensor_data_rx_apod;
    
    % Save Full Synthetic Aperture Data Generated by k-Wave
    filename = ['scratch/rf_data_tx_elem_', num2str(tx_elmt_idx), '.mat'];
    save(filename, 'rf_data', 'map_number'); % File Has Been Saved
    disp(['Data for TX element ', num2str(tx_elmt_idx), ' has been saved to file']);
    fprintf('This message is sent at time %s\n', datetime)
end